# Generated by Django 3.1.13 on 2021-11-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNAME', models.CharField(max_length=100)),
                ('STNGENAN', models.FloatField()),
                ('geometry', models.JSONField()),
            ],
        ),
    ]
