# Generated by Django 3.1.13 on 2021-11-29 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='PNAME',
            new_name='PSTATABB',
        ),
    ]
