# Generated by Django 3.1.13 on 2021-11-29 03:29

from django.db import migrations, models
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211129_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='geometry',
            field=models.JSONField(encoder=json.encoder.JSONEncoder),
        ),
    ]
